# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
import numpy as np

In [5]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [11]:
arr1=np.arange(0,10).reshape(2,5)
arr2=np.ones(10).reshape(2,5)
arr3=arr1.astype(np.int32)
arr4=arr2.astype(np.int32)

In [12]:
np.vstack((arr3 , arr4))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [13]:
np.hstack((arr3 , arr4))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [9]:
arr=np.arange(100).reshape(10,10)
arr[[0]]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [17]:
arr=np.arange(15).reshape(3,5)
arr2=arr.reshape(15)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [20]:
arr2.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [25]:
arr=np.arange(25).reshape(5,5)
np.sqrt(arr)*10

array([[ 0.        , 10.        , 14.14213562, 17.32050808, 20.        ],
       [22.36067977, 24.49489743, 26.45751311, 28.28427125, 30.        ],
       [31.6227766 , 33.1662479 , 34.64101615, 36.05551275, 37.41657387],
       [38.72983346, 40.        , 41.23105626, 42.42640687, 43.58898944],
       [44.72135955, 45.82575695, 46.9041576 , 47.95831523, 48.98979486]])

## Question:8

### Create 5x6 an array and find the mean?

In [10]:
arr=np.arange(30).reshape(5,6)
arr.mean()

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [11]:
arr.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [12]:
np.median(arr)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [13]:
arr.transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [18]:
arr=np.arange(16).reshape(4,4)
arr1=np.diagonal(arr)
np.sum(arr1)

30

## Question:13

### Find the determinant of the previous array in Q12?

In [20]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
np.linalg.det(arr)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [31]:
arr=np.arange(10)
np.percentile(arr , 5)

0.45

In [32]:
np.percentile(arr , 95)

8.549999999999999

## Question:15

### How to find if a given array has any null values?

In [25]:
arr=np.arange(10)

In [28]:
(arr==0).any()

True